[package]
name = "otlp-stdout-client"
version = "0.2.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "OpenTelemetry OTLP stdout client"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/rust/otlp-stdout-client"
homepage = "https://github.com/dev7a/lambda-otlp-forwarder"
keywords = ["opentelemetry", "otlp", "aws", "lambda", "telemetry"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[[example]]
name = "stdout_export"
path = "examples/stdout_export/main.rs"

[dependencies]
tokio.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-http.workspace = true
http.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
base64 = "0.21.7"
flate2 = "1.0.28"
bytes = "1.5.0"

[dev-dependencies]
sealed_test = "1.1.0"   
doc-comment = "0.3"
futures.workspace = true

