version = 0.1

[default.global.parameters]
stack_name = "otlp-stdout-kinesis-extension"
beta_features = "yes"

[default.build.parameters]
build_in_source = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "otlp-stdout-kinesis-extension"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
