[package]
name = "lambda-lw-http-router-macro"
version = "0.3.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Procedural macros for lambda-lw-http-router"
repository = "https://github.com/dev7a/serverless-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router/router-macro"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
darling.workspace = true

[dev-dependencies]
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
serde_json.workspace = true
tower.workspace = true
tokio.workspace = true
tokio-test.workspace = true
