[package]
name = "otlp-stdout-span-exporter"
version = "0.13.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A span exporter that writes OpenTelemetry spans to stdout in OTLP format"
repository = "https://github.com/dev7a/serverless-otlp-forwarder/tree/main/packages/rust/otlp-stdout-span-exporter"
homepage = "https://github.com/dev7a/serverless-otlp-forwarder"
documentation = "https://docs.rs/otlp-stdout-span-exporter"
readme = "README.md"
keywords = ["opentelemetry", "otlp", "tracing", "aws", "lambda"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[dependencies]
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-proto.workspace = true
tokio.workspace = true
async-trait.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
flate2.workspace = true
prost.workspace = true
doc-comment.workspace = true
log.workspace = true
bon.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serial_test.workspace = true
