[package]
name = "lambda-otel-utils"
version = "0.2.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "OpenTelemetry utilities for AWS Lambda"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/rust/lambda-otel-utils"
homepage = "https://github.com/dev7a/lambda-otlp-forwarder"
keywords = ["opentelemetry", "otlp", "aws", "lambda", "telemetry"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[[example]]
name = "tracing_example"
path = "examples/tracing_example.rs"

[dependencies]
tokio.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-http.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
aws_lambda_events.workspace = true
lambda_runtime.workspace = true
http.workspace = true
otlp-stdout-client.workspace = true
otlp-sigv4-client.workspace = true
thiserror.workspace = true
pin-project = "1.1.0"
opentelemetry-aws = { version = "0.15.0", features = ["detector-aws-lambda"] }
opentelemetry-semantic-conventions = { version = "0.27.0", features = ["semconv_experimental"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter", "json"] }
rustc_version_runtime = "0.3.0"

[dev-dependencies]
sealed_test = "1.1.0"   
doc-comment = "0.3"
serde_json.workspace = true
reqwest.workspace = true
