title: Serverless OTLP Forwarder
description: Serverless OpenTelemetry data forwarding for AWS Lambda
theme: just-the-docs
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
url: https://dev7a.github.io/serverless-otlp-forwarder

# Theme settings
heading_anchors: true
footer_content: "Copyright &copy; 2024. Distributed under the <a href=\"https://github.com/dev7a/serverless-otlp-forwarder/blob/main/LICENSE\">MIT license.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Theme
color_scheme: theme

# Breadcrumbs settings
breadcrumb_home_label: 'Home'
breadcrumb_separator: '/'
enable_breadcrumbs: true

# Google Fonts
google_fonts:
  - url: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap'

# External navigation links
nav_external_links:
  - title: Serverless OTLP Forwarder on GitHub
    url: https://github.com/dev7a/serverless-otlp-forwarder
    hide_icon: false

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap

mermaid:
  version: "9.1.6"

# Build settings
markdown: kramdown

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_enabled: true

# Navigation
aux_links:
  "View on GitHub": "https://github.com/dev7a/serverless-otlp-forwarder"
  "Edit on GitHub": "https://github.com/dev7a/serverless-otlp-forwarder/edit/main/docs/"

# GitHub edit link settings
gh_edit_link: false
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/dev7a/serverless-otlp-forwarder"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"
gh_root: ""

back_to_top: true
back_to_top_text: "Back to top"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

